# 첫번째 시도

```
테스트 1 〉	통과 (0.04ms, 10.3MB)
테스트 2 〉	통과 (0.05ms, 10.2MB)
테스트 3 〉	통과 (0.03ms, 10.2MB)
테스트 4 〉	통과 (0.34ms, 10.3MB)
테스트 5 〉	통과 (1.35ms, 10.2MB)
테스트 6 〉	통과 (3.85ms, 10.3MB)
테스트 7 〉	통과 (23.79ms, 10.4MB)
테스트 8 〉	통과 (78.23ms, 10.1MB)
테스트 9 〉	통과 (0.07ms, 10.2MB)
테스트 10 〉	통과 (2.61ms, 10.2MB)
테스트 11 〉	통과 (0.02ms, 10.3MB)
테스트 12 〉	통과 (3.58ms, 10.3MB)
테스트 13 〉	통과 (0.43ms, 10MB)
테스트 14 〉	통과 (0.32ms, 10.1MB)
테스트 15 〉	통과 (0.06ms, 10.2MB)
테스트 16 〉	통과 (0.06ms, 10.2MB)
테스트 17 〉	통과 (0.18ms, 10.1MB)
테스트 18 〉	실패 (0.04ms, 10.1MB)
테스트 19 〉	실패 (0.13ms, 10.3MB)
```
```pythoh
def solution(k, dungeons):
    global answer,check
    answer = 0
    check=[0]*len(dungeons)

    def dfs(remain) :
        global answer,check
        if sum([remain >= jj[0] for jj in dungeons]) ==0:
            can=sum(check)
            if can > answer :
                answer = can
            return 

        for idx,j in enumerate(dungeons) :
            if check[idx] == 0 and  remain >= j[0]:
                check[idx] =1
                dfs(remain - j[1])
                check[idx]=0


    dfs(k)
    return answer
 ```


# 두번째 시도
- check 한 내역도 같이 추가해서 다시 방문할 곳이 없다는 것을 확인해야하는데 

```python
# 던전 개수 최대 8개 
# dfs ?

# check list사용
# 남은양 피로도와 index를 input으로 받았음. -> index는 필요한지 모르겠음. -> 어차피 던전 전체를 매번 순회하기 때문

# 탐색할 것의 길이가 작음.

        
        
def solution(k, dungeons):
    global answer,check
    answer = 0
    check=[0 for _ in range(len(dungeons))]
    
    def dfs(remain) :
        global answer,check

        if sum([remain >= jj[0] and check[j]==0 for j,jj in enumerate(dungeons)]) ==0: # 여기 추가 했음.
            can = sum(check)
            if can > answer :
                answer = can
            return 

        for idx,j in enumerate(dungeons) :
            if (check[idx] == 0)and(remain >= j[0]):
                check[idx] =1
                dfs(remain - j[1])
                check[idx]=0


    dfs(k)
    return answer

```
